{
 "title": "e-shop-observability-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage - User Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:4000\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Carts Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:4003\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Products Service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:4002\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users{instance=\"localhost:4000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_users{job=\"users service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created Carts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 8 },
   "targets": [
    { "expr": "created_carts", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Viewed Items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 8 },
   "targets": [
    { "expr": "viewed_item{}" }
   ]
  },
  {
   "title": "Viewed Items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 8 },
   "targets": [
    { "expr": "created_item{}" }
   ]
  },
  {
   "title": "Purchased Carts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "rate(orders{job=\"users service\"}[24h])"
    }
   ]
  },
  {
   "title": "Emptied Carts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 19 },
   "targets": [
    {
     "expr": "emptied_carts{instance=\"localhost:4003\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}