apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    name: products
  namespace: e-shop
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 4002
  selector:
    name: products
  type: LoadBalancer